# Generated by Django 5.0.6 on 2024-09-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_jobapplication_cv'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='JobApplications',
        ),
    ]
