# Generated by Django 5.0.6 on 2024-09-20 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_jobapplication_jobapplications'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('highest_qualification', models.CharField(max_length=50)),
                ('course_specialization', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=10)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('cv', models.FileField(upload_to='cv_uploads/')),
                ('applied_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='JobApplications',
        ),
    ]
