# Generated by Django 5.0.6 on 2024-10-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_jobapplication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('job_description', models.TextField()),
                ('cv', models.FileField(upload_to='cvs/')),
            ],
        ),
    ]
