# Generated by Django 5.0.6 on 2024-10-20 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_applyjobapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_date_to_apply',
            field=models.DateField(blank=True, null=True),
        ),
    ]
